# Generated by Django 2.1.5 on 2019-02-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20190210_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
