# Generated by Django 2.1.5 on 2019-02-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='scout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports.Scout'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
        ),
        migrations.AddField(
            model_name='metric',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport'),
        ),
        migrations.AddField(
            model_name='media',
            name='sports_of_interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport'),
        ),
        migrations.AddField(
            model_name='fan',
            name='sport_of_interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport'),
        ),
        migrations.AddField(
            model_name='fan',
            name='team_supported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
