# Generated by Django 2.1.9 on 2019-06-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20190619_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
