# Generated by Django 2.2.7 on 2019-11-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_education'),
        ('sports', '0006_auto_20191111_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballratings',
            name='ratedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basketball_ratings', to='users.Profile'),
        ),
    ]
