# Generated by Django 2.1.10 on 2019-07-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skype',
        ),
    ]
