# Generated by Django 2.1.10 on 2019-09-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
