# Generated by Django 2.1.10 on 2019-07-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(upload_to='cover_photos'),
        ),
    ]
