# Generated by Django 2.1.10 on 2019-09-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='education',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institutionType',
        ),
        migrations.RemoveField(
            model_name='education',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='education',
            name='place',
        ),
        migrations.RemoveField(
            model_name='education',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='metrics',
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(blank=True, to='users.Education'),
        ),
    ]
