# Generated by Django 2.1.10 on 2019-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190910_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
