# Generated by Django 2.1.10 on 2019-09-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190917_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
    ]
