# Generated by Django 2.1.10 on 2019-09-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='club_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
