# Generated by Django 2.1.10 on 2019-07-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_photo',
        ),
    ]
