# Generated by Django 2.1.10 on 2019-07-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190704_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_to_run_100m',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
