# Generated by Django 2.1.10 on 2019-09-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190911_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='enthusiasts', to='users.Profile'),
        ),
    ]
